server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 15
    jpa:
      show_sql: true
      format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
